Updates OBS conversion to fully support RC v0.1
unfoldingWord-dev/dokuwiki-to-rc pull request #8
Opened 2017-01-11 02:49 UTC by neutrinog

Related to https://github.com/unfoldingWord-dev/door43.org/issues/366

* This updated completely removes github support since we are no longer storing translations there and adds full support for git.door43.org.
* The converted OBS now fully implements the RC 1.0 spec

2017-01-11 12:01 UTC, phillip-hopper requested changes
The class comment says this is for converting from Dokuwiki to RC, but the changes in the code don't appear to work with Dokuwiki. Please provide more explanation.

The conversion for OBS is not working. To run it, use this command:
```
python3 execute.py convert-obs --lang en --gitrepo https://github.com/Door43/d43-en --outdir ~/obs-en
```

2017-01-11 12:01 UTC, phillip-hopper commented on converters/obs_converter.py
> +        if 'github' not in git_repo and 'file://' not in git_repo and 'git.door43' not in git_repo:
Add dokuwiki repos are on github. What is the purpose of including 'git.door43' here?

2017-01-11 12:01 UTC, phillip-hopper commented on converters/obs_converter.py
> +            files_to_download.append(str(i).zfill(2) + '.md')
All dokuwiki files end with .txt, not .md

2017-01-11 15:26 UTC, jag3773 commented
@phillip-hopper is Correct.  @neutrinog The source for the data should remain unchanged.

Phil's example is perfect, except don't run that for English!

2017-01-11 22:50 UTC, neutrinog commented
ah ok. I couldn't find anything in github so I thought we were switching to gogs. Easy fix.

2017-01-12 19:59 UTC, neutrinog commented
Ok switched back to just supporting dokuwiki from github and added some additional improvements to parsing titles and added some content tests.

2017-01-13 13:35 UTC, phillip-hopper commented
@neutrinog Looks like there is an error in `test-setup.py`.

2017-01-13 15:40 UTC, jag3773 commented
Note that we have no rush here... changes are coming to reflect the RC 0.2 spec instead of 0.1.

2017-04-25 18:52 UTC, neutrinog commented
This is ready for another look but I can't figure out why coverage keeps failing.

2017-04-26 21:24 UTC, neutrinog commented on converters/obs_converter.py
> +        if 'github' not in git_repo and 'file://' not in git_repo and 'git.door43' not in git_repo:
this has been fixed.

2017-04-26 21:25 UTC, neutrinog commented on converters/obs_converter.py
> +            files_to_download.append(str(i).zfill(2) + '.md')
this has been fixed.

2017-05-02 12:48 UTC, merged